model:
  model : 3
  hidden_dimension: 3

dataset:
  datasets : ['MNIST', 'FashionMNIST', 'CIFAR10', 'KMNIST']
  batch_size : 512


optimizer:
  epochs : 100
  lr : 1e-4
  gamma : 0.8


plot:
  n_images : 10 
  show_training : False
  show_pieces : False
  show_rec : False

paths:
  net_weights : /home/x2030admin/andrea/encoders/models/
  images : /home/x2030admin/andrea/encoders/images
  models: /home/x2030admin/andrea/encoders/models
