model:
  vae : True
  hidden_dimension: 3


dataset:
  datasets : ['MNIST', 'FashionMNIST', 'CIFAR10', 'KMNIST']
  batch_size : 32

optimizer:
  epochs : 50
  lr : 1e-4
  gamma : 0.8

plot:
  n_images : 10 
  show_training : False
  show_pieces : False
  show_rec : True

paths:
  net_weights : /home/andrea/Scrivania/Tesi/encoders/models/
  images : /home/andrea/Scrivania/Tesi/encoders/images
  models: /home/andrea/Scrivania/Tesi/encoders/models